# Generated by Django 4.2.6 on 2023-11-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter the name of the category.', max_length=150),
        ),
    ]
