# Generated by Django 4.2.6 on 2023-11-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desctiption',
            new_name='description',
        ),
    ]
